dose-amigos/dose-amigos-ionic

app/dose-event-card/dose-event-card.component.html
Issue #17: Replaces "his" with "their".
Closes #17.
=> Issue #17: Replaces "his" with "their".

app/app.ts, app/dose-amigos-user-service/dose-amigos-user-mocks.ts, app/dose-amigos-user-service/dose-amigos-user.service.spec.ts, app/dose-amigos-user-service/dose-amigos-user.service.ts, app/dose-event-service/dose-event.mocks.ts, app/pages/amigos/amigos.html, app/pages/amigos/amigos.spec.ts, app/pages/amigos/amigos.ts
Issue #3: Amigos Page
Implements Amigos Page.
Adds DoseAmigosUserService.
Adds DoseAmigosUser mocks.
Updates Mock Events to pull users from mock users.
Closes #3.
=> Issue #3: Amigos Page

app/amigo-share-request-card/amigo-share-request-card.component.html, app/amigo-share-request-card/amigo-share-request-card.component.spec.ts, app/amigo-share-request-card/amigo-share-request-card.component.ts, app/amigo-share-request-service/amigo-share-request.mocks.ts, app/amigo-share-request-service/amigo-share-request.service.spec.ts, app/amigo-share-request-service/amigo-share-request.service.ts, app/amigo-share-request/amigo-share-request.ts, app/app.ts, app/pages/amigo-requests/amigo-requests.html, app/pages/amigo-requests/amigo-requests.scss, app/pages/amigo-requests/amigo-requests.spec.ts, app/pages/amigo-requests/amigo-requests.ts, app/pages/page-list.ts, app/theme/app.core.scss
Issue #15: Amigo Requests Page
Creates the Amigo Requests Page.
Creates amigo-share-request-card component.
Creates AmigoShareRequest object.
=> Issue #15: Amigo Requests Page

app/dose-event/dose-event.ts, app/dose-medication/dose-medication.ts, app/dose-series/dose-series.ts
Created domain objects for DoseEvent, DoseMedication, and DoseSeries.  These objects will be used in the Dose page which will be in later commits.
=> Added Domain Objects for DoseEvent, DoseMedication, and DoseSeries

app/app.ts, app/dose-event-service/dose-event-mocks.ts, app/dose-event-service/dose-event-service.spec.ts, app/dose-event-service/dose-event.service.ts, app/dose-medication-service/dose-medication-mocks.ts, app/dose-medication-service/dose-medication-service.spec.ts, app/dose-medication-service/dose-medication.service.ts
This is a brand new bull request for the dose page services.
=> Added DoseMedicationService and DoseEventService Objects

app/amigo-request-create-component/amigo-request-create.component.html, app/amigo-request-create-component/amigo-request-create.component.scss, app/amigo-request-create-component/amigo-request-create.component.ts, app/pages/amigo-requests/amigo-requests.html, app/pages/amigo-requests/amigo-requests.ts, app/pages/amigos/amigos.html, app/pages/amigos/amigos.ts, app/pages/new-amigo-request/new-amigo-request.html, app/pages/new-amigo-request/new-amigo-request.scss, app/pages/new-amigo-request/new-amigo-request.spec.ts, app/pages/new-amigo-request/new-amigo-request.ts, app/pages/page-list.ts, app/theme/app.core.scss
Issue #27: Amigo Request Creation
Creates AmigoRequestCreateComponent (FAB).
Adds this FAB to Amigos page.
Adds this FAB to Amigo Requests page.
Creates NewAmigoRequestPage.
=> Issue #27: Amigo Request Creation

app/dose-event-slider/dose-event-slider.component.html, app/dose-event-slider/dose-event-slider.component.ts, app/pages/dose/dose.html, app/pages/dose/dose.spec.ts, app/pages/dose/dose.ts
Had to create a new PR to merge changes.  This is the same as #31 which I closed.
=> Added files supporting the look of the dose page. Closes #29

app/angular2-jwt.ts, app/app.ts, app/auth-service/auth.service.ts, app/backend-config/backend-config.ts, app/dose-medication-service/dose-medication-service.spec.ts, app/dose-medication-service/dose-medication.service.ts, app/pages/page-list.ts, app/pages/testing/testing.html, app/pages/testing/testing.ts, package.json, test/gulpfile.ts
Issue #42: Updates DoseMedicationService to use AuthHttp.
Updates DoseMedicationService to use AuthHttp.
Copies angular2-jwt into project due to import/export compile issues.
Makes integration testing page.
Fixes npm test just so it runs (didn't fix tests).
=> Issue #42: Updates DoseMedicationService to use AuthHttp.

app/feed-event-service/feed-event-service.spec.ts, app/feed-event-service/feed-event-service.ts
Updates FeedEventService to use AuthHttp.
=> Issue #44: FeedEventService Integration

app/dose-event-fab/dose-event-fab.component.html, app/dose-event-fab/dose-event-fab.component.ts, app/dose-event-slider/dose-event-slider.component.html, app/dose-event-slider/dose-event-slider.component.ts, app/pages/dose/dose.html, app/pages/dose/dose.ts
This PR does the following:
1. Checking the FAB places a checkmark-circle by each medication.
2. Sliding and clicking the Taken button places a checkmark-circle icon by the specified medication.
3. Sliding and clicking the Snooze button places a clock icon by the specified medication.
4. Actions button slides the row revealing Taken/Snooze buttons, as long as the slider has been previously slid (Bug?)
Closes #32.
=> Added checkbox, snooze, and fab button functionality

app/amigo-share-request-card/amigo-share-request-card.component.html, app/amigo-share-request-service/amigo-share-request.mocks.ts, app/dose-amigos-user-service/dose-amigos-user-mocks.ts, app/dose-amigos-user/dose-amigos-user.ts, app/feed-event-card/feed-event-card.component.html, app/user-status-card/user-status-card.component.html
Adds a "picture" property to amigos.
Shows the new "picture" url or falls back to a person icon.
Closes #54.
=> Issue #54: Amigo Avatar

app/dose-event-service/dose-event-mocks-two.ts, app/dose-event-service/dose-event.service.ts, app/pages/dose/dose.html, app/pages/dose/dose.ts
Submitting this PR so @mckoon can see the loadPrev() and loadNext() methods.  Created a mocks-two.ts file to test, but I could not get it to work.  This PR does not break anything best I can tell.  If anyone has any suggestions on how to get the dose events page to refresh, I would appreciate it very much.  Also interested in the correct way to set the currentDate var in dost.ts.
=> Issue #55. Created loadPrev() and loadNext(). Currently does not work.

app/dose-event-service/dose-event-mocks-three.ts, app/dose-event-service/dose-event-mocks-two.ts, app/dose-event-service/dose-event.service.ts, app/pages/dose/dose.html, app/pages/dose/dose.ts
Adds commit on top of PR #56 to fix issues with "this", etc.
=> Issue #55: Fixed PR

app/app.ts, app/dose-amigos-user-service/dose-amigos-user.service.ts, app/dose-series-service/dose-series.service.ts, app/dose-series/dose-series.ts, app/pages/new-dose-medication/new-dose-medication.spec.ts, app/pages/new-dose-medication/new-dose-medication.ts, package.json
Creates DoseSeriesService that uses AuthHttp.
Updates new-dose-medication to call save() on it.
=> Issue #64: Creates DoseSeriesService

app/feed-event-card/feed-event-card.component.html, app/feed-event-card/feed-event-card.scss, app/theme/app.core.scss
Removes the social buttons on the feed event card.
Adds wording around the action to make a sentence.
Conditionally styles the action text.
Red if MISSED, green if TAKEN.
=> Issue #72: Clean up FeedEventCard UI

app/amigo-share-request-service/amigo-share-request.mocks.ts, app/dose-amigos-user-service/dose-amigos-user-mocks.ts, app/dose-amigos-user/dose-amigos-user.ts, app/dose-time-service/dose-time.service.spec.ts, app/dose-time-service/dose-time.service.ts, app/feed-event/feed-event.ts, app/last-dose/last-dose.component.html, app/last-dose/last-dose.component.ts, app/next-dose/next-dose.component.html, app/next-dose/next-dose.component.ts
Converts Dates on User object to numbers for server combatibility.
Changes icon and styling when no next/previous dose dates.
Shows N/A when no dose dates.
=> Issue #76: User Status Card UI

app/dose-series-service/dose-series-mocks.ts, app/med-list-event/med-list-event.component.html, app/med-list-event/med-list-event.component.ts, app/pages/med-list/med-list.html, app/pages/med-list/med-list.spec.ts, app/pages/med-list/med-list.ts
make the med list use doseSeries objects
=> Issue #78: Update Med List Page to use DoseSeries Objects

app/day-of-week/day-of-week.ts, app/day-of-week/days-of-week.ts, app/pages/new-dose-medication/new-dose-medication.html, app/pages/new-dose-medication/new-dose-medication.ts
Adds Setting Days of the Week for Dose Series.
=> Issue #83: Dose Series Days of Week

app/dose-event-slider/dose-event-slider.component.html
Sliders on dose page now displays correct dose amount.  Closes issue #86
=> Added dose amounts to slider component. Closes Issue #86

app/app.ts, app/dose-notifications/dose-notifications.ts, config.xml
Still testing, but here it is so far.
=> Geoffreygraddy issue 41 notifications

app/app.ts, app/dose-notifications/dose-notifications.ts
=> Issue #41 Added dose-notifications to project

app/dose-series-slider/dose-series-slider.component.html, app/pages/med-list/med-list.ts
=> Issue #94: Fix missing ';' and danger class the Delete button.

app/dose-notifications/dose-notifications.ts
Don't cancel triggered events.
Leave them in the phone's notifications list.
=> Issue #96: Cancel Only Scheduled
